### ISSUE TITLE
Crash on ATMF Dev

### ISSUE THREAD

**Issue by furtabs** [origami-games/quazi-modded#2]
https://hastebin.com/ijolizowox.rb

**Comment by grian32** [comment]
Report this to the modpack maker, we don't develop that modpack.

**Comment by dvitski** [comment]
> Report this to the modpack maker, we don't develop that modpack.

But the crash is our mod though

**Comment by furtabs** [comment]
Im the modpack dev

**Comment by grian32** [comment]
oh, ignore me then lol sorry

**Comment by dvitski** [comment]
> It's something to do with the client initialiser calling a method in a class that has server-side code

Needs testing
